/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.30.0-g12e132a (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.30.0-g12e132a"
#endif
#define SDL_REVISION_NUMBER 0
